base/views.py
from flask import Blueprint, render_template, abort
from jinja2 import TemplateNotFound

blueprint = Blueprint('invenio_web', __name__,
                        template_folder='templates', static_folder='static')


@blueprint.route('/')
def home():
    try:
        return render_template('index.html')
    except TemplateNotFound:
        abort(404)

@blueprint.route('/<page>')
def show(page):
    try:
        return render_template('pages/%s.html' % page)
    except TemplateNotFound:
        abort(404)

base/templates/footer.html
<section class="documentation">
	<div class="container">
		<div class="row">
			<a href="{{url_for('invenio_web.show', page = 'getting-started')}}">
				<div class="col-md-6 linkme a">
					<h5>Getting started<span class="fa fa-long-arrow-right"></span></h5>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos beatae neque ratione doloremque ex quasi, dolorum distinctio. Sed, molestiae labo.</p>
				</div>
			</a>
			<a href="{{url_for('invenio_web.show', page = 'documentation')}}">
				<div class="col-md-6 linkme b">
					<h5>Documentation<span class="fa fa-long-arrow-right"></span></h5>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Velit facere culpa hic sint doloribus. Sint consequuntur ullam, iure nulla vel, odit!</p>
				</div>
			</a>
		</div>
	</div>
</section>
<footer>
	<div class="footer-top">
		<div class="container">
			<div class="row">
				<nav class="col-md-12">
					<ul>
						<li class="title">DOCS</li>
						<li>Documentation</li>
						<li>Getting Started</li>
						<li>Modules</li>
						<li>Download</li>
					</ul>
					<ul>
						<li class="title">ABOUT</li>
						<li>Contact</li>
						<li>Support</li>
						<li>Forum</li>
						<li>Contribute</li>
					</ul>
					<ul>
						<li class="title">RESOURCES</li>
						<li>News</li>
						<li>Team</li>
						<li>Showcase</li>
					</ul>
		
					<ul>
						<li class="title">CONNECT</li>
						<li>GitHub</li>
						<li>Twitter</li>
						<li>Newsletter</li>
						<li>TIND</li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<span class="pull-right">Invenio Software © 2014</span>
				</div>
			</div>
		</div>
	</div>
</footer>

base/templates/header.html
<header>
	<nav class="navbar">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a href="{{url_for('invenio_web.home')}}" class="navbar-brand">
					<img src="{{ url_for('static', filename='img/invenio.png')}}" alt="">
				</a>
			</div>
			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="{{url_for('invenio_web.show', page = 'getting-started')}}">Getting Started</a></li>
					<li><a href="{{url_for('invenio_web.show', page = 'documentation')}}">Docs</a></li>
					<li><a href="{{url_for('invenio_web.show', page = 'showcase')}}">Showcase</a></li>
					<li><a href="{{url_for('invenio_web.show', page = 'news')}}">News</a></li>
					<li><a href="{{url_for('invenio_web.show', page = 'support')}}">Support</a></li>
					<li><a href="https://forum.invenio-software.org/">Forum</a></li>
				</ul>
			</div>
		</div>
	</nav>
</header>

base/templates/index.html
{% extends 'page.html' %}

{% block body %}
	<style>

	</style>
	<section class="intro">
		{% include 'header.html' %}
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="row">
						<div id="main-left" class="col-md-6">
							<div class="welcome">
								<h3>Say something here</h3>
								<h6>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero harum minus repellat laborum cum aut placeat illum.</h6>
							</div>
							<div class="actions">
								<form action="{{url_for('invenio_web.show', page='downloads')}}">
									<button class="btn white">Download</button>
								</form>
								<form action="{{url_for('invenio_web.show', page='documentation')}}">
									<button class="btn">Docs & Help</button>
								</form>
							</div>
						</div>
						<div class="col-md-6">
							<img class="img-screenshot" src="{{url_for('static', filename='img/cds-demo-image.svg')}}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="social-bar">
			<div class="container">
				<div class="row">
					<div>
						<ul class="col-md-6">
							<li class="fa"></li>
							<li class="fa"><a href="http://github.com/inveniosoftware/invenio"><span class="fa fa-code-fork"></span>108 forks</a></li>
							<li class="fa"><a href="https://twitter.com/inveniosoftware"><span class="fa fa-twitter"></span>100 followers</a></li>
						</ul>
					</div>
					<div class="col-md-6">
						<form id="newsletter-submit" class="form-group pull-right" action="">
							<div class="form-newsletter-inner">
								<input class="form-control" type="email" placeholder="Enter your email for the latest Invenio news">
								<input class="" type="submit" value="Subscribe">
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="desc">
		<div class="container">
			<div class="row">
				<div id="top-desc" class="col-md-10 col-md-offset-1">
					<h6>Run your own digital library or document repository on the web</h6>
					<p>
						Invenio is a <a href="">​free software</a> suite enabling you to run your own <a href="">​digital library</a> or document repository on the web. The technology offered by the software covers all aspects of digital library management from document ingestion through classification, indexing, and curation to dissemination. Invenio complies with standards such as the <a href="">​Open Archives Initiative</a> metadata harvesting protocol (OAI-PMH) and uses ​MARC 21 as its underlying bibliographic format. The flexibility and performance of Invenio make it a comprehensive solution for management of document repositories of moderate to large sizes (several millions of records).
					</p>
					<p>
						Invenio has been originally developed at <a href="">​CERN</a> to run the <a href="">​CERN document server</a>, managing over 1,000,000 bibliographic records in high-energy physics since 2002, covering articles, books, journals, photos, videos, and more. Invenio is being co-developed by an international collaboration comprising institutes such as <a href="">​CERN</a>, <a href="">​DESY</a>, <a href="">​EPFL</a>, <a href="">​FNAL</a>, <a href="">​SLAC</a> and is being used by about thirty scientific institutions worldwide (see <a href="">demo</a>).
					</p>
				</div>
			</div>
			<div>
				<div id="features" class="col-md-10 col-md-offset-1">
					<div class="row feature-row">
						<div class="feature-img col-md-6"></div>
						<div class="feature-text col-md-6">
							<h6>Navigable collection tree</h6>
							<ul>
								<li>Documents organised in collections</li>
								<li>Regular and virtual collection trees</li>
								<li>Customizable portalboxes for each collection</li>
								<li>At CERN, over 1,000,000 documents in 700 collections</li>
							</ul>
						</div>
					</div>
					<div class="row feature-row">
						<div class="feature-text col-md-6">
							<h6>Powerful search engine</h6>
							<ul>
								<li>Specially designed indexes to provide fast search speed for repositories of up to 2,000,000 records</li>
								<li>Customizable simple and advanced search interfaces</li>
								<li>Combined metadata, fulltext and citation search in one go</li>
								<li>Results clustering by collection</li>
							</ul>
						</div>
						<div class="feature-img col-md-6"></div>
					</div>
					<div class="row feature-row">
						<div class="feature-img col-md-6"></div>
						<div class="feature-text col-md-6">
							<h6>Flexible metadata</h6>
							<ul>
								<li>Standard metadata format (MARC)</li>
								<li>Handling articles, books, theses, photos, videos, museum objects and more</li>
								<li>Customizable display and linking rules</li>
							</ul>
						</div>
					</div>
					<div class="row feature-row">
						<div class="feature-text col-md-6">
							<h6>User personalization</h6>
							<ul>
								<li>user-defined document baskets</li>
								<li>user-defined automated email notification alerts</li>
								<li>basket-sharing within user groups</li>
								<li>Amazon-like user comments for documents in repository and shared baskets</li>
							</ul>
						</div>
						<div class="feature-img col-md-6"></div>
					</div>
					<div class="row feature-row">
						<div id="filetypes" class="feature-text col-md-8 col-md-offset-2" style="text-align:center;">
							<h6>with multiple output formats..</h6>
							<ul >
								<li><span class="fa fa-file"></span><div class="thumb-text">HTML</div></li>
								<li><span class="fa fa-file"></span><div class="thumb-text">XML</div></li>
								<li><span class="fa fa-file"></span><div class="thumb-text">MARC</div></li>
								<li><span class="fa fa-file"></span><div class="thumb-text">OAI</div></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	{% include "footer.html" %}
{% endblock %}

base/templates/layout.html
<!doctype html>
<title>{% block title %}{% endblock %} | {{ config.CFG_SITE_NAME }}</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<script src="{{ config.JQUERY }}"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<header>
  <h1>Mozilla Persona Example</h1>
  <div class="authbar">

  </div>
</header>
{% block body %}{% endblock %}

base/templates/page.html
<!doctype html>
<title>{% block title %}{% endblock %} | {{ config.CFG_SITE_NAME }}</title>
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<script src="{{ config.JQUERY }}"></script>
<script src="{{ url_for('static', filename='components/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='components/bootstrap/dist/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='components/font-awesome/css/font-awesome.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='components/open-sans-fontface/open-sans.css') }}">
<body>
{% block body %}{% endblock %}	
</body>

base/templates/pages/base.html
{% extends 'page.html' %}

{% block body %}
	<section class="basic-page intro">
		{% include 'header.html' %}
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h3>Title goes here</h3>
					<h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h5>
				</div>
			</div>
		</div>
		<div class="intro-bar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="row">
							<h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h5>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="main-content">
		<div class="container">
			<div class="row">
				<div class="col-md-4 left-sidebar"></div>
				<div class="col-m-8 content-box"></div>
			</div>
		</div>
	</section>
	{% include "footer.html" %}
{% endblock %}

base/templates/pages/documentation.html
{% extends 'page.html' %}

{% block body %}
	<section class="basic-page intro">
		{% include 'header.html' %}
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h3>Invenio Documentation</h3>
					<h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h5>
				</div>
			</div>
		</div>
		<div class="intro-bar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h5>Questions? Head over to our <a href="">Mailing List</a> to chat with others using the framework.</h5>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="main-content">
		
	</section>
	{% include "footer.html" %}
{% endblock %}

base/templates/pages/downloads.html
{% extends 'page.html' %}

{% block body %}
	<section class="basic-page intro">
		{% include 'header.html' %}
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h3>Downloads</h3>
					<h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h5>
				</div>
			</div>
		</div>
		<div class="intro-bar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h5>Ready to start building your own Invenio instance! Go to our <a href="{{url_for('invenio_web.show', page = 'documentation')}}">Documentation & Guides</a> page.</h5>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="main-content">
		<div class="container">
			<div class="row">
				<div id="left-sidebar" class="col-md-3">
					<ul data-spy="affix" data-offset-top="60" data-offset-bottom="600">
						<li>
							<span>Downloads</span>
							<ul class="nav" role="tablist">
								<li >Latest Stable Releases</li>
								<li>Source Code Repository</li>
							</ul>							
						</li>
					</ul>
				</div>
				<div id="content-box" class="col-md-9" data-spy="scroll" data-target="#left-sidebar">
					<h2 class="title-box">Downloads</h2>
					<div id="latest">
						<h4>Latest Stable Releases</h4>
						<ul>
							<li>
								Invenio v1.1 release series: (recommended)<br>
								<p><a href="">invenio-1.1.4.tar.gz</a> - 2014-08-31 - 10004166 bytes - <a href="">md5</a> - <a href="">sig</a></p>
							</li>
							<li>
								Invenio v1.0 release series: (old stable)<br>
								<p><a href="">invenio-1.0.7.tar.gz</a> - 2014-08-31 - 8384886 bytes - <a href="">md5</a> - <a href="">sig</a></p>
							</li>
							<li>
								Invenio v0.99 release series: (very old stable)<br>
								<p><a href="">invenio-0.99.9.tar.gz</a> - 2014-01-31 - 5917427 bytes - <a href="">md5</a> - <a href="">sig</a></p>
							</li>
						</ul>
					</div>
					<div id="repo">
						<h4>Source Code Repository</h4>
						<p>The development sources can be accessed via Git:</p>
						<pre class="wiki"><span class="newline">$</span> git clone http://invenio-software.org/repo/invenio<br><span class="newline">$</span> git checkout master # or maint-M.N, or next, or pu...
						</pre>
						<p>
							You can also browse Invenio source code repository via our
							<a href="http://invenio-software.org/repo/invenio">git web interface</a>
							and read the source code documentation and snippets via our
							<a href="http://invenio-software.org/code-browser/">code browser</a>.
						</p>
						<p>If you are testing development sources instead of using regular tarball releases, we advise you to run autotools like this:</p>
						<pre class="wiki"><span class="newline">$</span> rm -rf autom4te.cache/<br><span class="newline">$</span> aclocal-1.11<br><span class="newline">$</span> automake-1.11 -a<br><span class="newline">$</span> autoconf
						</pre>
						<p>and proceed with the installation as usual (<tt>./configure</tt>, etc). This will generate you a proper "development snapshot" version number of the form <tt>0.99.1.1457-19fb4</tt> meaning that you are running a development snapshot that started off from 0.99.1 on a branch that is currently at its 1457th commit after 0.99.1 and that the latest commit in this branch is SHA1 19fb4.
						</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	{% include "footer.html" %}
{% endblock %}

base/templates/pages/getting-started.html
{% extends 'page.html' %}

{% block body %}
	<section class="basic-page intro">
		{% include 'header.html' %}
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h3>Getting Started with Invenio</h3>
					<h5>Build your own digital library or document repository quick and easy</h5>
				</div>
			</div>
		</div>
		<div class="intro-bar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h5>Check out our <a href="{{url_for('invenio_web.show', page = 'documentation')}}">Documentation & Guides</a> for more details.</h5>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="main-content">
		<div class="container">
			<div class="row">
				<div id="left-sidebar" class="col-md-3" >
					<ul data-spy="affix" data-offset-top="60" data-offset-bottom="600">
						<li>
							<span>Getting Started</span>
							<ul class="nav" role="tablist" >
								<li>Overview</li>
								<li>Prerequisites
									<ul>
										<li>Debian/Ubuntu LTS</li>
										<li>Centos / RHEL</li>
										<li>OS X</li>
										<li>Extra tools</li>
									</ul>
								</li>
								<li>Creating an Invenio overlay</li>
							</ul>							
						</li>
					</ul>
				</div>
				<div id="content-box" class="col-md-9" data-spy="scroll" data-target="#left-sidebar">
					{% include '/pages/docs/installation.html' %}
					<div id="latest">
						<h4>Latest Stable Releases</h4>
						<ul>
							<li>
								Invenio v1.1 release series: (recommended)<br>
								<p><a href="">invenio-1.1.4.tar.gz</a> - 2014-08-31 - 10004166 bytes - <a href="">md5</a> - <a href="">sig</a></p>
							</li>
							<li>
								Invenio v1.0 release series: (old stable)<br>
								<p><a href="">invenio-1.0.7.tar.gz</a> - 2014-08-31 - 8384886 bytes - <a href="">md5</a> - <a href="">sig</a></p>
							</li>
							<li>
								Invenio v0.99 release series: (very old stable)<br>
								<p><a href="">invenio-0.99.9.tar.gz</a> - 2014-01-31 - 5917427 bytes - <a href="">md5</a> - <a href="">sig</a></p>
							</li>
						</ul>
					</div>
					<div id="repo">
						<h4>Source Code Repository</h4>
						<p>The development sources can be accessed via Git:</p>
						<pre class="wiki"><span class="newline">$</span> git clone http://invenio-software.org/repo/invenio<br><span class="newline">$</span> git checkout master # or maint-M.N, or next, or pu...
						</pre>
						<p>
							You can also browse Invenio source code repository via our
							<a href="http://invenio-software.org/repo/invenio">git web interface</a>
							and read the source code documentation and snippets via our
							<a href="http://invenio-software.org/code-browser/">code browser</a>.
						</p>
						<p>If you are testing development sources instead of using regular tarball releases, we advise you to run autotools like this:</p>
						<pre class="wiki"><span class="newline">$</span> rm -rf autom4te.cache/<br><span class="newline">$</span> aclocal-1.11<br><span class="newline">$</span> automake-1.11 -a<br><span class="newline">$</span> autoconf
						</pre>
						<p>and proceed with the installation as usual (<tt>./configure</tt>, etc). This will generate you a proper "development snapshot" version number of the form <tt>0.99.1.1457-19fb4</tt> meaning that you are running a development snapshot that started off from 0.99.1 on a branch that is currently at its 1457th commit after 0.99.1 and that the latest commit in this branch is SHA1 19fb4.
						</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	{% include "footer.html" %}
{% endblock %}

base/templates/pages/showcase.html
{% extends 'page.html' %}

{% block body %}
	<section class="basic-page intro">
		{% include 'header.html' %}
		<div class="container">
			<div class="row">
				<div class="col-md-12">	
					<h3>Demo & Example Sites</h3>
					<h5>Here are listed several Invenio installations that you can have a look, in order to see it in action</h5>	
				</div>
			</div>
		</div>
		<div class="intro-bar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h5>Ready to build your own Invenio instance. Jump to our <a href="{{url_for('invenio_web.show', page = 'getting-started')}}">Getting Started</a> page</h5>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="main-content">
		
	</section>
	{% include "footer.html" %}
{% endblock %}

base/templates/pages/support.html
{% extends 'page.html' %}

{% block body %}
	<section class="basic-page intro">
		{% include 'header.html' %}
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h3>Title goes here</h3>
					<h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h5>
				</div>
			</div>
		</div>
		<div class="intro-bar">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h5>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</h5>
					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="main-content">
		
	</section>
	{% include "footer.html" %}
{% endblock %}